package main

import "fmt"

type s1 struct {
	name string
	ch   rune
}

// ([\d|\w]{4})$
// ",'\\u$1'},
var ssss = []s1{

	{"nf-cod-bookmark", '\ueaa5'},
	{"nf-fa-bookmark", '\uf02e'},
	{"nf-md-bookmarkf", '\u00c0'},
	{"nf-oct-bookmark", '\uf461'},
	{"nf-fa-bookmark_o", '\uf097'},
	{"nf-md-bookmark_checkf", '\u00c1'},
	{"nf-md-bookmark_minusf", '\u09cc'},
	{"nf-md-bookmark_multiplef", '\u0e15'},
	{"nf-md-bookmark_musicf", '\u00c2'},
	{"nf-md-bookmark_offf", '\u09ce'},
	{"nf-md-bookmark_outlinef", '\u00c3'},
	{"nf-md-bookmark_plusf", '\u00c5'},
	{"nf-md-bookmark_removef", '\u00c6'},
	{"nf-md-comment_bookmarkf", '\u15ae'},
	{"nf-md-message_bookmarkf", '\u15ac'},
	{"nf-md-call_received", '\U000f00fa'},

	{"nf-cod-search", '\uea6d'},
	{"nf-fa-search", '\uf002'},
	{"nf-oct-search", '\uf422'},
	{"nf-seti-search", '\ue68f'},
	{"nf-cod-search_fuzzy", '\uec0d'},
	{"nf-cod-search_stop", '\ueb4e'},
	{"nf-fa-search_minus", '\uf010'},
	{"nf-fa-search_plus", '\uf00e'},
	{"nf-md-account_searchf", '\u0016'},
	{"nf-md-airplane_searchf", '\u1883'},
	{"nf-md-archive_searchf", '\u1769'},
	{"nf-md-book_searchf", '\u0e84'},
	{"nf-md-briefcase_searchf", '\u0a2d'},
	{"nf-md-calendar_searchf", '\u094c'},
	{"nf-md-card_searchf", '\u1074'},
	{"nf-md-clipboard_searchf", '\u161e'},
	{"nf-md-cloud_searchf", '\u0956'},
	{"nf-md-comment_searchf", '\u0a3c'},
	{"nf-md-database_searchf", '\u0866'},
	{"nf-md-email_searchf", '\u0961'},
	{"nf-md-feature_searchf", '\u0a49'},
	{"nf-md-file_searchf", '\u0c7c'},
	{"nf-md-folder_searchf", '\u0968'},
	{"nf-md-home_searchf", '\u13b0'},
	{"nf-md-image_searchf", '\u0977'},
	{"nf-md-layers_searchf", '\u1206'},
	{"nf-md-map_searchf", '\u0984'},
	{"nf-md-movie_searchf", '\u11d2'},
	{"nf-md-note_searchf", '\u1653'},
	{"nf-md-printer_searchf", '\u1457'},
	{"nf-md-search_webf", '\u070f'},
	{"nf-md-select_searchf", '\u1204'},
	{"nf-md-selection_searchf", '\u1205'},
	{"nf-md-shield_searchf", '\u0d9a'},
	{"nf-md-shopping_searchf", '\u0f84'},
	{"nf-md-store_searchf", '\u18d2'},
	{"nf-md-tab_searchf", '\u199e'},
	{"nf-md-table_searchf", '\u090f'},
	{"nf-md-tag_searchf", '\u1907'},
	{"nf-md-text_searchf", '\u13b8'},
	{"nf-seti-code_search", '\ue644'},
	{"nf-md-account_search_outlinef", '\u0935'},
	{"nf-md-archive_search_outlinef", '\u176a'},
	{"nf-md-book_search_outlinef", '\u0e85'},
	{"nf-md-briefcase_search_outlinef", '\u0c42'},
	{"nf-md-card_search_outlinef", '\u1075'},
	{"nf-md-clipboard_search_outlinef", '\u161f'},
	{"nf-md-clipboard_text_searchf", '\u1622'},
	{"nf-md-cloud_search_outlinef", '\u0957'},
	{"nf-md-comment_search_outlinef", '\u0a3d'},
	{"nf-md-credit_card_searchf", '\u1647'},
	{"nf-md-database_search_outlinef", '\u1636'},
	{"nf-md-email_search_outlinef", '\u0962'},
	{"nf-md-feature_search_outlinef", '\u0a4a'},
	{"nf-md-file_search_outlinef", '\u0c7d'},
	{"nf-md-folder_search_outlinef", '\u0969'},
	{"nf-md-home_search_outlinef", '\u13b1'},
	{"nf-md-image_search_outlinef", '\u0978'},
	{"nf-md-layers_search_outlinef", '\u1207'},
	{"nf-md-map_search_outlinef", '\u0985'},
	{"nf-md-movie_search_outlinef", '\u11d3'},
	{"nf-md-nfc_search_variantf", '\u0e53'},
	{"nf-md-note_search_outlinef", '\u1654'},
	{"nf-md-shopping_search_outlinef", '\u1a6f'},
	{"nf-md-store_search_outlinef", '\u18d3'},
	{"nf-md-tag_search_outlinef", '\u1908'},
	{"nf-md-text_box_searchf", '\u0eae'},
	{"nf-md-text_search_variantf", '\u1a7e'},
	{"nf-md-toy_brick_searchf", '\u1292'},
	{"nf-md-clipboard_text_search_outlinef", '\u1623'},
	{"nf-md-credit_card_search_outlinef", '\u1648'},
	{"nf-md-text_box_search_outlinef", '\u0eaf'},
	{"nf-md-toy_brick_search_outlinef", '\u1293'},
	{"nf-fa-searchengin", '\ued23'},
}

func main() {
	for i, v := range ssss {
		fmt.Printf("%d %s %c\n", i, v.name, v.ch)
	}
}
