Data:
 - Group: "Normal"
   foreground: "#e0e2ea"
   background: "#14161b"

 - Group: "Comment"
   foreground: "#9b9ea4"

 - Group: "Constant"
   foreground: "#e0e2ea"

 - Group: "String"
   foreground: "#b3f6c0"

 - Group: "Character"
   foreground: "#e0e2ea"

 - Group: "Number"
   foreground: "#e0e2ea"

 - Group: "Boolean"
   foreground: "#e0e2ea"

 - Group: "Identifier"
   foreground: "#a6dbff"

 - Group: "Function"
   foreground: "#8cf8f7"

 - Group: "Statement"
   foreground: "#e0e2ea"
   bold: true

 - Group: "Conditional"
   foreground: "#e0e2ea"
   bold: true

 - Group: "Repeat"
   foreground: "#e0e2ea"
   bold: true

 - Group: "Label"
   foreground: "#e0e2ea"
   bold: true

 - Group: "Operator"
   foreground: "#e0e2ea"

 - Group: "Keyword"
   foreground: "#e0e2ea"
   bold: true

 - Group: "Exception"
   foreground: "#e0e2ea"
   bold: true

 - Group: "PreProc"
   foreground: "#e0e2ea"

 - Group: "Include"
   foreground: "#e0e2ea"

 - Group: "Define"
   foreground: "#e0e2ea"

 - Group: "Macro"
   foreground: "#e0e2ea"

 - Group: "Type"
   foreground: "#e0e2ea"

 - Group: "StorageClass"
   foreground: "#e0e2ea"

 - Group: "Structure"
   foreground: "#e0e2ea"

 - Group: "Typedef"
   foreground: "#e0e2ea"

 - Group: "Special"
   foreground: "#8cf8f7"

 - Group: "SpecialChar"
   foreground: "#8cf8f7"

 - Group: "Tag"
   foreground: "#8cf8f7"

 - Group: "Delimiter"
   foreground: "#e0e2ea"

 - Group: "SpecialComment"
   foreground: "#8cf8f7"

 - Group: "Error"
   foreground: "#eef1f8"
   background: "#590008"

 - Group: "Todo"
   foreground: "#e0e2ea"
   bold: true

 - Group: "Underlined"
   underline: true

 - Group: "Bold"
   true: 6

 - Group: "Italic"
   true: 6

 - Group: "Ignore"
   foreground: "#e0e2ea"
   background: "#14161b"

 - Group: "ErrorMsg"
   foreground: "#ffc0b9"

 - Group: "WarningMsg"
   foreground: "#fce094"

 - Group: "Folded"
   foreground: "#9b9ea4"
   background: "#2c2e33"

 - Group: "FoldColumn"
   foreground: "#4f5258"

 - Group: "DiffAdd"
   foreground: "#eef1f8"
   background: "#5523"

 - Group: "DiffChange"
   foreground: "#eef1f8"
   background: "#4f5258"

 - Group: "DiffDelete"
   foreground: "#ffc0b9"
   bold: true

 - Group: "DiffText"
   foreground: "#eef1f8"
   background: "#7373"

 - Group: "SignColumn"
   foreground: "#4f5258"

 - Group: "CursorLine"
   background: "#2c2e33"

 - Group: "CursorColumn"
   background: "#2c2e33"

 - Group: "ColorColumn"
   background: "#4f5258"

 - Group: "Conceal"
   foreground: "#4f5258"

 - Group: "LineNr"
   foreground: "#4f5258"

 - Group: "CursorLineNr"
   bold: true

 - Group: "StatusLine"
   foreground: "#2c2e33"
   background: "#c4c6cd"

 - Group: "StatusLineNC"
   foreground: "#c4c6cd"
   background: "#2c2e33"

 - Group: "Whitespace"
   foreground: "#4f5258"

 - Group: "NonText"
   foreground: "#4f5258"

 - Group: "SpecialKey"
   foreground: "#4f5258"

 - Group: "Pmenu"
   background: "#2c2e33"

 - Group: "PmenuSel"
   foreground: "#2c2e33"
   blend: 0
   background: "#e0e2ea"

 - Group: "PmenuSbar"
   background: "#2c2e33"

 - Group: "PmenuThumb"
   background: "#4f5258"

 - Group: "TabLine"
   foreground: "#c4c6cd"
   background: "#2c2e33"

 - Group: "TabLineFill"
   foreground: "#c4c6cd"
   background: "#2c2e33"

 - Group: "TabLineSel"
   bold: true

 - Group: "Title"
   foreground: "#e0e2ea"
   bold: true

 - Group: "Visual"
   background: "#4f5258"

 - Group: "VisualNOS"
   background: "#4f5258"

 - Group: "QuickFixLine"
   foreground: "#8cf8f7"

 - Group: "Search"
   foreground: "#eef1f8"
   background: "#6b5300"

 - Group: "IncSearch"
   foreground: "#7080d"
   background: "#fce094"

 - Group: "MatchParen"
   background: "#4f5258"
   bold: true

 - Group: "SpellBad"
   special: "#ffc0b9"
   undercurl: true

 - Group: "SpellCap"
   special: "#fce094"
   undercurl: true

 - Group: "SpellRare"
   special: "#8cf8f7"
   undercurl: true

 - Group: "SpellLocal"
   special: "#b3f6c0"
   undercurl: true

 - Group: "@ibl.indent.char.1"
   foreground: "#4f5258"

 - Group: "@ibl.scope.char.1"
   foreground: "#4f5258"
   nocombine: true

 - Group: "@ibl.scope.underline.1"
   underline: true
   special: "#4f5258"

 - Group: "@ibl.whitespace.char.1"
   foreground: "#4f5258"

 - Group: "@lsp.mod.deprecated"
   special: "#ffc0b9"
   strikethrough: true

 - Group: "@lsp.type.event"
   foreground: "#e0e2ea"

 - Group: "@markup.italic"
   italic: true

 - Group: "@markup.strikethrough"
   strikethrough: true

 - Group: "@markup.strong"
   bold: true

 - Group: "@markup.underline"
   underline: true

 - Group: "@module.builtin"
   foreground: "#8cf8f7"

 - Group: "@variable"
   foreground: "#e0e2ea"

