package devicon

import "path/filepath"

type Icon struct {
	Key         string
	Icon        string
	Color       string
	Cterm_color string
	Name        string
}

func array_to_map(icon []Icon) (ret map[string]Icon) {
	ret = make(map[string]Icon)
	for _, v := range icon {
		ret[v.Key] = v
	}
	return ret
}

var map_icons_by_fileName = array_to_map(icons_by_fileName)
var map_icons_by_file_extension = array_to_map(icons_by_file_extension)

func FindIconPath(filename string) (ret Icon, err error) {
	var name = filepath.Base(filename)
	if v, ok := map_icons_by_fileName[name]; ok {
		return v, nil
	}
	x := filepath.Ext(filename)
	if len(x) > 1 {
		if x[0] == '.' {
			x = x[1:]
		}
	}
	if v, ok := map_icons_by_file_extension[x]; ok {
		return v, nil
	}
	return
}

var icons_by_fileName = []Icon{
	{Key: ".babelrc",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Babelrc",
	},
	{Key: ".bash_profile",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "BashProfile",
	},
	{Key: ".bashrc",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Bashrc",
	},
	{Key: ".dockerignore",
		Icon:        "󰡨",
		Color:       "#458ee6",
		Cterm_color: "68",
		Name:        "Dockerfile",
	},
	{Key: ".ds_store",
		Icon:        "",
		Color:       "#41535b",
		Cterm_color: "239",
		Name:        "DsStore",
	},
	{Key: ".editorconfig",
		Icon:        "",
		Color:       "#fff2f2",
		Cterm_color: "255",
		Name:        "EditorConfig",
	},
	{Key: ".env",
		Icon:        "",
		Color:       "#faf743",
		Cterm_color: "227",
		Name:        "Env",
	},
	{Key: ".eslintrc",
		Icon:        "",
		Color:       "#4b32c3",
		Cterm_color: "56",
		Name:        "Eslintrc",
	},
	{Key: ".eslintignore",
		Icon:        "",
		Color:       "#4b32c3",
		Cterm_color: "56",
		Name:        "EslintIgnore",
	},
	{Key: ".git-blame-ignore-revs",
		Icon:        "",
		Color:       "#f54d27",
		Cterm_color: "196",
		Name:        "GitBlameIgnore",
	},
	{Key: ".gitattributes",
		Icon:        "",
		Color:       "#f54d27",
		Cterm_color: "196",
		Name:        "GitAttributes",
	},
	{Key: ".gitconfig",
		Icon:        "",
		Color:       "#f54d27",
		Cterm_color: "196",
		Name:        "GitConfig",
	},
	{Key: ".gitignore",
		Icon:        "",
		Color:       "#f54d27",
		Cterm_color: "196",
		Name:        "GitIgnore",
	},
	{Key: ".gitlab-ci.yml",
		Icon:        "",
		Color:       "#e24329",
		Cterm_color: "196",
		Name:        "GitlabCI",
	},
	{Key: ".gitmodules",
		Icon:        "",
		Color:       "#f54d27",
		Cterm_color: "196",
		Name:        "GitModules",
	},
	{Key: ".gtkrc-2.0",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "GTK",
	},
	{Key: ".gvimrc",
		Icon:        "",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "Gvimrc",
	},
	{Key: ".justfile",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Justfile",
	},
	{Key: ".luaurc",
		Icon:        "",
		Color:       "#00a2ff",
		Cterm_color: "75",
		Name:        "Luaurc",
	},
	{Key: ".mailmap",
		Icon:        "󰊢",
		Color:       "#f54d27",
		Cterm_color: "196",
		Name:        "Mailmap",
	},
	{Key: ".npmignore",
		Icon:        "",
		Color:       "#E8274B",
		Cterm_color: "197",
		Name:        "NPMIgnore",
	},
	{Key: ".npmrc",
		Icon:        "",
		Color:       "#E8274B",
		Cterm_color: "197",
		Name:        "NPMrc",
	},
	{Key: ".nuxtrc",
		Icon:        "󱄆",
		Color:       "#00c58e",
		Cterm_color: "42",
		Name:        "NuxtConfig",
	},
	{Key: ".nvmrc",
		Icon:        "",
		Color:       "#5FA04E",
		Cterm_color: "71",
		Name:        "node",
	},
	{Key: ".prettierrc",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierrc.cjs",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierrc.js",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierrc.json",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierrc.json5",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierrc.mjs",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierrc.toml",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierrc.yaml",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierrc.yml",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: ".prettierignore",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierIgnore",
	},
	{Key: ".settings.json",
		Icon:        "",
		Color:       "#854CC7",
		Cterm_color: "98",
		Name:        "SettingsJson",
	},
	{Key: ".SRCINFO",
		Icon:        "󰣇",
		Color:       "#0f94d2",
		Cterm_color: "67",
		Name:        "SRCINFO",
	},
	{Key: ".vimrc",
		Icon:        "",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "Vimrc",
	},
	{Key: ".Xauthority",
		Icon:        "",
		Color:       "#e54d18",
		Cterm_color: "196",
		Name:        "Xauthority",
	},
	{Key: ".xinitrc",
		Icon:        "",
		Color:       "#e54d18",
		Cterm_color: "196",
		Name:        "XInitrc",
	},
	{Key: ".Xresources",
		Icon:        "",
		Color:       "#e54d18",
		Cterm_color: "196",
		Name:        "Xresources",
	},
	{Key: ".xsession",
		Icon:        "",
		Color:       "#e54d18",
		Cterm_color: "196",
		Name:        "Xsession",
	},
	{Key: ".zprofile",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Zshprofile",
	},
	{Key: ".zshenv",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Zshenv",
	},
	{Key: ".zshrc",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Zshrc",
	},
	{Key: "_gvimrc",
		Icon:        "",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "Gvimrc",
	},
	{Key: "_vimrc",
		Icon:        "",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "Vimrc",
	},
	{Key: "avif",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Avif",
	},
	{Key: "brewfile",
		Icon:        "",
		Color:       "#701516",
		Cterm_color: "52",
		Name:        "Brewfile",
	},
	{Key: "bspwmrc",
		Icon:        "",
		Color:       "#2f2f2f",
		Cterm_color: "236",
		Name:        "BSPWM",
	},
	{Key: "build",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "BazelBuild",
	},
	{Key: "build.gradle",
		Icon:        "",
		Color:       "#005f87",
		Cterm_color: "24",
		Name:        "GradleBuildScript",
	},
	{Key: "build.zig.zon",
		Icon:        "",
		Color:       "#f69a1b",
		Cterm_color: "172",
		Name:        "ZigObjectNotation",
	},
	{Key: "checkhealth",
		Icon:        "󰓙",
		Color:       "#75B4FB",
		Cterm_color: "75",
		Name:        "Checkhealth",
	},
	{Key: "cmakelists.txt",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "CMakeLists",
	},
	{Key: "code_of_conduct",
		Icon:        "",
		Color:       "#E41662",
		Cterm_color: "161",
		Name:        "CodeOfConduct",
	},
	{Key: "code_of_conduct.md",
		Icon:        "",
		Color:       "#E41662",
		Cterm_color: "161",
		Name:        "CodeOfConduct",
	},
	{Key: "commit_editmsg",
		Icon:        "",
		Color:       "#f54d27",
		Cterm_color: "196",
		Name:        "GitCommit",
	},
	{Key: "commitlint.config.js",
		Icon:        "󰜘",
		Color:       "#2b9689",
		Cterm_color: "30",
		Name:        "CommitlintConfig",
	},
	{Key: "commitlint.config.ts",
		Icon:        "󰜘",
		Color:       "#2b9689",
		Cterm_color: "30",
		Name:        "CommitlintConfig",
	},
	{Key: "compose.yaml",
		Icon:        "󰡨",
		Color:       "#458ee6",
		Cterm_color: "68",
		Name:        "Dockerfile",
	},
	{Key: "compose.yml",
		Icon:        "󰡨",
		Color:       "#458ee6",
		Cterm_color: "68",
		Name:        "Dockerfile",
	},
	{Key: "config",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Config",
	},
	{Key: "containerfile",
		Icon:        "󰡨",
		Color:       "#458ee6",
		Cterm_color: "68",
		Name:        "Dockerfile",
	},
	{Key: "copying",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "License",
	},
	{Key: "copying.lesser",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "License",
	},
	{Key: "docker-compose.yaml",
		Icon:        "󰡨",
		Color:       "#458ee6",
		Cterm_color: "68",
		Name:        "Dockerfile",
	},
	{Key: "docker-compose.yml",
		Icon:        "󰡨",
		Color:       "#458ee6",
		Cterm_color: "68",
		Name:        "Dockerfile",
	},
	{Key: "dockerfile",
		Icon:        "󰡨",
		Color:       "#458ee6",
		Cterm_color: "68",
		Name:        "Dockerfile",
	},
	{Key: "eslint.config.cjs",
		Icon:        "",
		Color:       "#4b32c3",
		Cterm_color: "56",
		Name:        "Eslintrc",
	},
	{Key: "eslint.config.js",
		Icon:        "",
		Color:       "#4b32c3",
		Cterm_color: "56",
		Name:        "Eslintrc",
	},
	{Key: "eslint.config.mjs",
		Icon:        "",
		Color:       "#4b32c3",
		Cterm_color: "56",
		Name:        "Eslintrc",
	},
	{Key: "eslint.config.ts",
		Icon:        "",
		Color:       "#4b32c3",
		Cterm_color: "56",
		Name:        "Eslintrc",
	},
	{Key: "ext_typoscript_setup.txt",
		Icon:        "",
		Color:       "#FF8700",
		Cterm_color: "208",
		Name:        "TypoScriptSetup",
	},
	{Key: "favicon.ico",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Favicon",
	},
	{Key: "fp-info-cache",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCadCache",
	},
	{Key: "fp-lib-table",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCadFootprintTable",
	},
	{Key: "FreeCAD.conf",
		Icon:        "",
		Color:       "#CB333B",
		Cterm_color: "160",
		Name:        "FreeCADConfig",
	},
	{Key: "gemfile$",
		Icon:        "",
		Color:       "#701516",
		Cterm_color: "52",
		Name:        "Gemfile",
	},
	{Key: "gnumakefile",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Makefile",
	},
	{Key: "go.mod",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "GoMod",
	},
	{Key: "go.sum",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "GoSum",
	},
	{Key: "go.work",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "GoWork",
	},
	{Key: "gradlew",
		Icon:        "",
		Color:       "#005f87",
		Cterm_color: "24",
		Name:        "GradleWrapperScript",
	},
	{Key: "gradle.properties",
		Icon:        "",
		Color:       "#005f87",
		Cterm_color: "24",
		Name:        "GradleProperties",
	},
	{Key: "gradle-wrapper.properties",
		Icon:        "",
		Color:       "#005f87",
		Cterm_color: "24",
		Name:        "GradleWrapperProperties",
	},
	{Key: "groovy",
		Icon:        "",
		Color:       "#4a687c",
		Cterm_color: "24",
		Name:        "Groovy",
	},
	{Key: "gruntfile.babel.js",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Gruntfile",
	},
	{Key: "gruntfile.coffee",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Gruntfile",
	},
	{Key: "gruntfile.js",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Gruntfile",
	},
	{Key: "gruntfile.ts",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Gruntfile",
	},
	{Key: "gtkrc",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "GTK",
	},
	{Key: "gulpfile.babel.js",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "Gulpfile",
	},
	{Key: "gulpfile.coffee",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "Gulpfile",
	},
	{Key: "gulpfile.js",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "Gulpfile",
	},
	{Key: "gulpfile.ts",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "Gulpfile",
	},
	{Key: "hypridle.conf",
		Icon:        "",
		Color:       "#00aaae",
		Cterm_color: "37",
		Name:        "Hypridle",
	},
	{Key: "hyprland.conf",
		Icon:        "",
		Color:       "#00aaae",
		Cterm_color: "37",
		Name:        "Hyprland",
	},
	{Key: "hyprlock.conf",
		Icon:        "",
		Color:       "#00aaae",
		Cterm_color: "37",
		Name:        "Hyprlock",
	},
	{Key: "hyprpaper.conf",
		Icon:        "",
		Color:       "#00aaae",
		Cterm_color: "37",
		Name:        "Hyprpaper",
	},
	{Key: "i18n.config.js",
		Icon:        "󰗊",
		Color:       "#7986cb",
		Cterm_color: "104",
		Name:        "I18nConfig",
	},
	{Key: "i18n.config.ts",
		Icon:        "󰗊",
		Color:       "#7986cb",
		Cterm_color: "104",
		Name:        "I18nConfig",
	},
	{Key: "i3blocks.conf",
		Icon:        "",
		Color:       "#e8ebee",
		Cterm_color: "255",
		Name:        "i3",
	},
	{Key: "i3status.conf",
		Icon:        "",
		Color:       "#e8ebee",
		Cterm_color: "255",
		Name:        "i3",
	},
	{Key: "ionic.config.json",
		Icon:        "",
		Color:       "#4f8ff7",
		Cterm_color: "33",
		Name:        "Ionic",
	},
	{Key: "cantorrc",
		Icon:        "",
		Color:       "#1c99f3",
		Cterm_color: "32",
		Name:        "Cantorrc",
	},
	{Key: "justfile",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Justfile",
	},
	{Key: "kalgebrarc",
		Icon:        "",
		Color:       "#1c99f3",
		Cterm_color: "32",
		Name:        "Kalgebrarc",
	},
	{Key: "kdeglobals",
		Icon:        "",
		Color:       "#1c99f3",
		Cterm_color: "32",
		Name:        "KDEglobals",
	},
	{Key: "kdenlive-layoutsrc",
		Icon:        "",
		Color:       "#83b8f2",
		Cterm_color: "110",
		Name:        "KdenliveLayoutsrc",
	},
	{Key: "kdenliverc",
		Icon:        "",
		Color:       "#83b8f2",
		Cterm_color: "110",
		Name:        "Kdenliverc",
	},
	{Key: "kritadisplayrc",
		Icon:        "",
		Color:       "#f245fb",
		Cterm_color: "201",
		Name:        "Kritadisplayrc",
	},
	{Key: "kritarc",
		Icon:        "",
		Color:       "#f245fb",
		Cterm_color: "201",
		Name:        "Kritarc",
	},
	{Key: "license",
		Icon:        "",
		Color:       "#d0bf41",
		Cterm_color: "185",
		Name:        "License",
	},
	{Key: "license.md",
		Icon:        "",
		Color:       "#d0bf41",
		Cterm_color: "185",
		Name:        "License",
	},
	{Key: "lxde-rc.xml",
		Icon:        "",
		Color:       "#909090",
		Cterm_color: "246",
		Name:        "LXDEConfigFile",
	},
	{Key: "lxqt.conf",
		Icon:        "",
		Color:       "#0192d3",
		Cterm_color: "32",
		Name:        "LXQtConfigFile",
	},
	{Key: "makefile",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Makefile",
	},
	{Key: "mix.lock",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "MixLock",
	},
	{Key: "mpv.conf",
		Icon:        "",
		Color:       "#3b1342",
		Cterm_color: "53",
		Name:        "Mpv",
	},
	{Key: "node_modules",
		Icon:        "",
		Color:       "#E8274B",
		Cterm_color: "197",
		Name:        "NodeModules",
	},
	{Key: "nuxt.config.cjs",
		Icon:        "󱄆",
		Color:       "#00c58e",
		Cterm_color: "42",
		Name:        "NuxtConfig",
	},
	{Key: "nuxt.config.js",
		Icon:        "󱄆",
		Color:       "#00c58e",
		Cterm_color: "42",
		Name:        "NuxtConfig",
	},
	{Key: "nuxt.config.mjs",
		Icon:        "󱄆",
		Color:       "#00c58e",
		Cterm_color: "42",
		Name:        "NuxtConfig",
	},
	{Key: "nuxt.config.ts",
		Icon:        "󱄆",
		Color:       "#00c58e",
		Cterm_color: "42",
		Name:        "NuxtConfig",
	},
	{Key: "package.json",
		Icon:        "",
		Color:       "#e8274b",
		Cterm_color: "197",
		Name:        "PackageJson",
	},
	{Key: "package-lock.json",
		Icon:        "",
		Color:       "#7a0d21",
		Cterm_color: "52",
		Name:        "PackageLockJson",
	},
	{Key: "PKGBUILD",
		Icon:        "",
		Color:       "#0f94d2",
		Cterm_color: "67",
		Name:        "PKGBUILD",
	},
	{Key: "platformio.ini",
		Icon:        "",
		Color:       "#f6822b",
		Cterm_color: "208",
		Name:        "Platformio",
	},
	{Key: "pom.xml",
		Icon:        "",
		Color:       "#7a0d21",
		Cterm_color: "52",
		Name:        "Maven",
	},
	{Key: "prettier.config.js",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: "prettier.config.cjs",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: "prettier.config.mjs",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: "prettier.config.ts",
		Icon:        "",
		Color:       "#4285F4",
		Cterm_color: "33",
		Name:        "PrettierConfig",
	},
	{Key: "procfile",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Procfile",
	},
	{Key: "PrusaSlicer.ini",
		Icon:        "",
		Color:       "#ec6b23",
		Cterm_color: "202",
		Name:        "PrusaSlicer",
	},
	{Key: "PrusaSlicerGcodeViewer.ini",
		Icon:        "",
		Color:       "#ec6b23",
		Cterm_color: "202",
		Name:        "PrusaSlicer",
	},
	{Key: "py.typed",
		Icon:        "",
		Color:       "#ffbc03",
		Cterm_color: "214",
		Name:        "Py.typed",
	},
	{Key: "QtProject.conf",
		Icon:        "",
		Color:       "#40cd52",
		Cterm_color: "77",
		Name:        "Qt",
	},
	{Key: "rakefile",
		Icon:        "",
		Color:       "#701516",
		Cterm_color: "52",
		Name:        "Rakefile",
	},
	{Key: "rmd",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Rmd",
	},
	{Key: "robots.txt",
		Icon:        "󰚩",
		Color:       "#5d7096",
		Cterm_color: "60",
		Name:        "RobotsTxt",
	},
	{Key: "security",
		Icon:        "󰒃",
		Color:       "#BEC4C9",
		Cterm_color: "251",
		Name:        "Security",
	},
	{Key: "security.md",
		Icon:        "󰒃",
		Color:       "#BEC4C9",
		Cterm_color: "251",
		Name:        "Security",
	},
	{Key: "settings.gradle",
		Icon:        "",
		Color:       "#005f87",
		Cterm_color: "24",
		Name:        "GradleSettings",
	},
	{Key: "svelte.config.js",
		Icon:        "",
		Color:       "#ff3e00",
		Cterm_color: "196",
		Name:        "SvelteConfig",
	},
	{Key: "sxhkdrc",
		Icon:        "",
		Color:       "#2f2f2f",
		Cterm_color: "236",
		Name:        "BSPWM",
	},
	{Key: "sym-lib-table",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCadSymbolTable",
	},
	{Key: "tailwind.config.js",
		Icon:        "󱏿",
		Color:       "#20c2e3",
		Cterm_color: "45",
		Name:        "TailwindConfig",
	},
	{Key: "tailwind.config.mjs",
		Icon:        "󱏿",
		Color:       "#20c2e3",
		Cterm_color: "45",
		Name:        "TailwindConfig",
	},
	{Key: "tailwind.config.ts",
		Icon:        "󱏿",
		Color:       "#20c2e3",
		Cterm_color: "45",
		Name:        "TailwindConfig",
	},
	{Key: "tmux.conf",
		Icon:        "",
		Color:       "#14ba19",
		Cterm_color: "34",
		Name:        "Tmux",
	},
	{Key: "tmux.conf.local",
		Icon:        "",
		Color:       "#14ba19",
		Cterm_color: "34",
		Name:        "Tmux",
	},
	{Key: "tsconfig.json",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "TSConfig",
	},
	{Key: "unlicense",
		Icon:        "",
		Color:       "#d0bf41",
		Cterm_color: "185",
		Name:        "License",
	},
	{Key: "vagrantfile$",
		Icon:        "",
		Color:       "#1563FF",
		Cterm_color: "27",
		Name:        "Vagrantfile",
	},
	{Key: "vlcrc",
		Icon:        "󰕼",
		Color:       "#ee7a00",
		Cterm_color: "208",
		Name:        "VLC",
	},
	{Key: "vercel.json",
		Icon:        "▲",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "Vercel",
	},
	{Key: "webpack",
		Icon:        "󰜫",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Webpack",
	},
	{Key: "weston.ini",
		Icon:        "",
		Color:       "#ffbb01",
		Cterm_color: "214",
		Name:        "Weston",
	},
	{Key: "workspace",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "BazelWorkspace",
	},
	{Key: "xmobarrc",
		Icon:        "",
		Color:       "#fd4d5d",
		Cterm_color: "203",
		Name:        "xmonad",
	},
	{Key: "xmobarrc.hs",
		Icon:        "",
		Color:       "#fd4d5d",
		Cterm_color: "203",
		Name:        "xmonad",
	},
	{Key: "xmonad.hs",
		Icon:        "",
		Color:       "#fd4d5d",
		Cterm_color: "203",
		Name:        "xmonad",
	},
	{Key: "xorg.conf",
		Icon:        "",
		Color:       "#e54d18",
		Cterm_color: "196",
		Name:        "XorgConf",
	},
	{Key: "xsettingsd.conf",
		Icon:        "",
		Color:       "#e54d18",
		Cterm_color: "196",
		Name:        "XSettingsdConf",
	},
}

var icons_by_file_extension = []Icon{
	{Key: "3gp",
		Icon:        "",
		Color:       "#FD971F",
		Cterm_color: "208",
		Name:        "3gp",
	},
	{Key: "3mf",
		Icon:        "󰆧",
		Color:       "#888888",
		Cterm_color: "102",
		Name:        "3DObjectFile",
	},
	{Key: "7z",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "7z",
	},
	{Key: "a",
		Icon:        "",
		Color:       "#dcddd6",
		Cterm_color: "253",
		Name:        "StaticLibraryArchive",
	},
	{Key: "aac",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "AdvancedAudioCoding",
	},
	{Key: "aif",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "AudioInterchangeFileFormat",
	},
	{Key: "aiff",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "AudioInterchangeFileFormat",
	},
	{Key: "ape",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "MonkeysAudio",
	},
	{Key: "apl",
		Icon:        "⍝",
		Color:       "#ffa500",
		Cterm_color: "214",
		Name:        "APL",
	},
	{Key: "ai",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Ai",
	},
	{Key: "android",
		Icon:        "",
		Color:       "#34a853",
		Cterm_color: "35",
		Name:        "Android",
	},
	{Key: "apk",
		Icon:        "",
		Color:       "#34a853",
		Cterm_color: "35",
		Name:        "apk",
	},
	{Key: "app",
		Icon:        "",
		Color:       "#9F0500",
		Cterm_color: "124",
		Name:        "App",
	},
	{Key: "applescript",
		Icon:        "",
		Color:       "#6d8085",
		Cterm_color: "66",
		Name:        "AppleScript",
	},
	{Key: "asc",
		Icon:        "󰦝",
		Color:       "#576d7f",
		Cterm_color: "242",
		Name:        "Asc",
	},
	{Key: "ass",
		Icon:        "󰨖",
		Color:       "#ffb713",
		Cterm_color: "214",
		Name:        "Ass",
	},
	{Key: "astro",
		Icon:        "",
		Color:       "#e23f67",
		Cterm_color: "197",
		Name:        "Astro",
	},
	{Key: "awk",
		Icon:        "",
		Color:       "#4d5a5e",
		Cterm_color: "240",
		Name:        "Awk",
	},
	{Key: "azcli",
		Icon:        "",
		Color:       "#0078d4",
		Cterm_color: "32",
		Name:        "AzureCli",
	},
	{Key: "bak",
		Icon:        "󰁯",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Backup",
	},
	{Key: "bash",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Bash",
	},
	{Key: "bat",
		Icon:        "",
		Color:       "#C1F12E",
		Cterm_color: "191",
		Name:        "Bat",
	},
	{Key: "bazel",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Bazel",
	},
	{Key: "bib",
		Icon:        "󱉟",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "BibTeX",
	},
	{Key: "bicep",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Bicep",
	},
	{Key: "bicepparam",
		Icon:        "",
		Color:       "#9f74b3",
		Cterm_color: "133",
		Name:        "BicepParameters",
	},
	{Key: "bin",
		Icon:        "",
		Color:       "#9F0500",
		Cterm_color: "124",
		Name:        "Bin",
	},
	{Key: "blade.php",
		Icon:        "",
		Color:       "#f05340",
		Cterm_color: "203",
		Name:        "Blade",
	},
	{Key: "blend",
		Icon:        "󰂫",
		Color:       "#ea7600",
		Cterm_color: "208",
		Name:        "Blender",
	},
	{Key: "bmp",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Bmp",
	},
	{Key: "bqn",
		Icon:        "⎉",
		Color:       "#2b7067",
		Cterm_color: "23",
		Name:        "BQN",
	},
	{Key: "blp",
		Icon:        "󰺾",
		Color:       "#5796E2",
		Cterm_color: "68",
		Name:        "Blueprint",
	},
	{Key: "brep",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "BoundaryRepresentation",
	},
	{Key: "bz",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Bz",
	},
	{Key: "bz2",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Bz2",
	},
	{Key: "bz3",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Bz3",
	},
	{Key: "bzl",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Bzl",
	},
	{Key: "c",
		Icon:        "",
		Color:       "#599eff",
		Cterm_color: "111",
		Name:        "C",
	},
	{Key: "c++",
		Icon:        "",
		Color:       "#f34b7d",
		Cterm_color: "204",
		Name:        "CPlusPlus",
	},
	{Key: "cache",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "Cache",
	},
	{Key: "cast",
		Icon:        "",
		Color:       "#FD971F",
		Cterm_color: "208",
		Name:        "Asciinema",
	},
	{Key: "cbl",
		Icon:        "⚙",
		Color:       "#005ca5",
		Cterm_color: "25",
		Name:        "Cobol",
	},
	{Key: "cc",
		Icon:        "",
		Color:       "#f34b7d",
		Cterm_color: "204",
		Name:        "CPlusPlus",
	},
	{Key: "ccm",
		Icon:        "",
		Color:       "#f34b7d",
		Cterm_color: "204",
		Name:        "CPlusPlusModule",
	},
	{Key: "cfg",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Configuration",
	},
	{Key: "cjs",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Cjs",
	},
	{Key: "clj",
		Icon:        "",
		Color:       "#8dc149",
		Cterm_color: "113",
		Name:        "Clojure",
	},
	{Key: "cljc",
		Icon:        "",
		Color:       "#8dc149",
		Cterm_color: "113",
		Name:        "ClojureC",
	},
	{Key: "cljs",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "ClojureJS",
	},
	{Key: "cljd",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "ClojureDart",
	},
	{Key: "cmake",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "CMake",
	},
	{Key: "cob",
		Icon:        "⚙",
		Color:       "#005ca5",
		Cterm_color: "25",
		Name:        "Cobol",
	},
	{Key: "cobol",
		Icon:        "⚙",
		Color:       "#005ca5",
		Cterm_color: "25",
		Name:        "Cobol",
	},
	{Key: "coffee",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Coffee",
	},
	{Key: "conf",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Conf",
	},
	{Key: "config.ru",
		Icon:        "",
		Color:       "#701516",
		Cterm_color: "52",
		Name:        "ConfigRu",
	},
	{Key: "cow",
		Icon:        "󰆚",
		Color:       "#965824",
		Cterm_color: "130",
		Name:        "CowsayFile",
	},
	{Key: "cp",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Cp",
	},
	{Key: "cpp",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Cpp",
	},
	{Key: "cppm",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Cppm",
	},
	{Key: "cpy",
		Icon:        "⚙",
		Color:       "#005ca5",
		Cterm_color: "25",
		Name:        "Cobol",
	},
	{Key: "cr",
		Icon:        "",
		Color:       "#c8c8c8",
		Cterm_color: "251",
		Name:        "Crystal",
	},
	{Key: "crdownload",
		Icon:        "",
		Color:       "#44cda8",
		Cterm_color: "43",
		Name:        "Crdownload",
	},
	{Key: "cs",
		Icon:        "󰌛",
		Color:       "#596706",
		Cterm_color: "58",
		Name:        "Cs",
	},
	{Key: "csh",
		Icon:        "",
		Color:       "#4d5a5e",
		Cterm_color: "240",
		Name:        "Csh",
	},
	{Key: "cshtml",
		Icon:        "󱦗",
		Color:       "#512bd4",
		Cterm_color: "56",
		Name:        "RazorPage",
	},
	{Key: "cson",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Cson",
	},
	{Key: "csproj",
		Icon:        "󰪮",
		Color:       "#512bd4",
		Cterm_color: "56",
		Name:        "CSharpProject",
	},
	{Key: "css",
		Icon:        "",
		Color:       "#42a5f5",
		Cterm_color: "75",
		Name:        "Css",
	},
	{Key: "csv",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Csv",
	},
	{Key: "cts",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Cts",
	},
	{Key: "cu",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "cuda",
	},
	{Key: "cue",
		Icon:        "󰲹",
		Color:       "#ed95ae",
		Cterm_color: "211",
		Name:        "Cue",
	},
	{Key: "cuh",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "cudah",
	},
	{Key: "cxx",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Cxx",
	},
	{Key: "cxxm",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Cxxm",
	},
	{Key: "d",
		Icon:        "",
		Color:       "#427819",
		Cterm_color: "28",
		Name:        "D",
	},
	{Key: "d.ts",
		Icon:        "",
		Color:       "#d59855",
		Cterm_color: "172",
		Name:        "TypeScriptDeclaration",
	},
	{Key: "dart",
		Icon:        "",
		Color:       "#03589C",
		Cterm_color: "25",
		Name:        "Dart",
	},
	{Key: "db",
		Icon:        "",
		Color:       "#dad8d8",
		Cterm_color: "188",
		Name:        "Db",
	},
	{Key: "dconf",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "Dconf",
	},
	{Key: "desktop",
		Icon:        "",
		Color:       "#563d7c",
		Cterm_color: "54",
		Name:        "DesktopEntry",
	},
	{Key: "diff",
		Icon:        "",
		Color:       "#41535b",
		Cterm_color: "239",
		Name:        "Diff",
	},
	{Key: "dll",
		Icon:        "",
		Color:       "#4d2c0b",
		Cterm_color: "52",
		Name:        "Dll",
	},
	{Key: "doc",
		Icon:        "󰈬",
		Color:       "#185abd",
		Cterm_color: "26",
		Name:        "Doc",
	},
	{Key: "Dockerfile",
		Icon:        "󰡨",
		Color:       "#458ee6",
		Cterm_color: "68",
		Name:        "Dockerfile",
	},
	{Key: "docx",
		Icon:        "󰈬",
		Color:       "#185abd",
		Cterm_color: "26",
		Name:        "Docx",
	},
	{Key: "dot",
		Icon:        "󱁉",
		Color:       "#30638e",
		Cterm_color: "24",
		Name:        "Dot",
	},
	{Key: "download",
		Icon:        "",
		Color:       "#44cda8",
		Cterm_color: "43",
		Name:        "Download",
	},
	{Key: "drl",
		Icon:        "",
		Color:       "#ffafaf",
		Cterm_color: "217",
		Name:        "Drools",
	},
	{Key: "dropbox",
		Icon:        "",
		Color:       "#0061FE",
		Cterm_color: "27",
		Name:        "Dropbox",
	},
	{Key: "dump",
		Icon:        "",
		Color:       "#dad8d8",
		Cterm_color: "188",
		Name:        "Dump",
	},
	{Key: "dwg",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "AutoCADDwg",
	},
	{Key: "dxf",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "AutoCADDxf",
	},
	{Key: "ebook",
		Icon:        "",
		Color:       "#eab16d",
		Cterm_color: "215",
		Name:        "Ebook",
	},
	{Key: "ebuild",
		Icon:        "",
		Color:       "#4C416E",
		Cterm_color: "60",
		Name:        "GentooBuild",
	},
	{Key: "edn",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Edn",
	},
	{Key: "eex",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Eex",
	},
	{Key: "ejs",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Ejs",
	},
	{Key: "elf",
		Icon:        "",
		Color:       "#9F0500",
		Cterm_color: "124",
		Name:        "Elf",
	},
	{Key: "el",
		Icon:        "",
		Color:       "#8172be",
		Cterm_color: "97",
		Name:        "Elisp",
	},
	{Key: "elc",
		Icon:        "",
		Color:       "#8172be",
		Cterm_color: "97",
		Name:        "Elisp",
	},
	{Key: "elm",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Elm",
	},
	{Key: "eln",
		Icon:        "",
		Color:       "#8172be",
		Cterm_color: "97",
		Name:        "Elisp",
	},
	{Key: "env",
		Icon:        "",
		Color:       "#faf743",
		Cterm_color: "227",
		Name:        "Env",
	},
	{Key: "eot",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "EmbeddedOpenTypeFont",
	},
	{Key: "epp",
		Icon:        "",
		Color:       "#FFA61A",
		Cterm_color: "214",
		Name:        "Epp",
	},
	{Key: "epub",
		Icon:        "",
		Color:       "#eab16d",
		Cterm_color: "215",
		Name:        "Epub",
	},
	{Key: "erb",
		Icon:        "",
		Color:       "#701516",
		Cterm_color: "52",
		Name:        "Erb",
	},
	{Key: "erl",
		Icon:        "",
		Color:       "#B83998",
		Cterm_color: "163",
		Name:        "Erl",
	},
	{Key: "ex",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Ex",
	},
	{Key: "exe",
		Icon:        "",
		Color:       "#9F0500",
		Cterm_color: "124",
		Name:        "Exe",
	},
	{Key: "exs",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Exs",
	},
	{Key: "f#",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Fsharp",
	},
	{Key: "f3d",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "Fusion360",
	},
	{Key: "f90",
		Icon:        "󱈚",
		Color:       "#734f96",
		Cterm_color: "97",
		Name:        "Fortran",
	},
	{Key: "fbx",
		Icon:        "󰆧",
		Color:       "#888888",
		Cterm_color: "102",
		Name:        "3DObjectFile",
	},
	{Key: "fcbak",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fcmacro",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fcmat",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fcparam",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fcscript",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fcstd",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fcstd1",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fctb",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fctl",
		Icon:        "",
		Color:       "#cb333b",
		Cterm_color: "160",
		Name:        "FreeCAD",
	},
	{Key: "fdmdownload",
		Icon:        "",
		Color:       "#44cda8",
		Cterm_color: "43",
		Name:        "Fdmdownload",
	},
	{Key: "flac",
		Icon:        "",
		Color:       "#0075aa",
		Cterm_color: "24",
		Name:        "FreeLosslessAudioCodec",
	},
	{Key: "flc",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "FIGletFontControl",
	},
	{Key: "flf",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "FIGletFontFormat",
	},
	{Key: "fnl",
		Icon:        "",
		Color:       "#fff3d7",
		Cterm_color: "230",
		Name:        "Fennel",
	},
	{Key: "fish",
		Icon:        "",
		Color:       "#4d5a5e",
		Cterm_color: "240",
		Name:        "Fish",
	},
	{Key: "fs",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Fs",
	},
	{Key: "fsi",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Fsi",
	},
	{Key: "fsscript",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Fsscript",
	},
	{Key: "fsx",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Fsx",
	},
	{Key: "gcode",
		Icon:        "󰐫",
		Color:       "#1471ad",
		Cterm_color: "32",
		Name:        "GCode",
	},
	{Key: "gd",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "GDScript",
	},
	{Key: "gemspec",
		Icon:        "",
		Color:       "#701516",
		Cterm_color: "52",
		Name:        "Gemspec",
	},
	{Key: "gif",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Gif",
	},
	{Key: "git",
		Icon:        "",
		Color:       "#F14C28",
		Cterm_color: "196",
		Name:        "GitLogo",
	},
	{Key: "glb",
		Icon:        "",
		Color:       "#FFB13B",
		Cterm_color: "214",
		Name:        "BinaryGLTF",
	},
	{Key: "gleam",
		Icon:        "",
		Color:       "#ffaff3",
		Cterm_color: "219",
		Name:        "Gleam",
	},
	{Key: "gnumakefile",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Makefile",
	},
	{Key: "go",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Go",
	},
	{Key: "godot",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "GodotProject",
	},
	{Key: "gql",
		Icon:        "",
		Color:       "#e535ab",
		Cterm_color: "199",
		Name:        "GraphQL",
	},
	{Key: "gradle",
		Icon:        "",
		Color:       "#005f87",
		Cterm_color: "24",
		Name:        "Gradle",
	},
	{Key: "graphql",
		Icon:        "",
		Color:       "#e535ab",
		Cterm_color: "199",
		Name:        "GraphQL",
	},
	{Key: "gresource",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "GTK",
	},
	{Key: "gv",
		Icon:        "󱁉",
		Color:       "#30638e",
		Cterm_color: "24",
		Name:        "Gv",
	},
	{Key: "gz",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Gz",
	},
	{Key: "h",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "H",
	},
	{Key: "haml",
		Icon:        "",
		Color:       "#eaeae1",
		Cterm_color: "255",
		Name:        "Haml",
	},
	{Key: "hx",
		Icon:        "",
		Color:       "#ea8220",
		Cterm_color: "208",
		Name:        "Haxe",
	},
	{Key: "hbs",
		Icon:        "",
		Color:       "#f0772b",
		Cterm_color: "202",
		Name:        "Hbs",
	},
	{Key: "hex",
		Icon:        "",
		Color:       "#2e63ff",
		Cterm_color: "27",
		Name:        "Hexadecimal",
	},
	{Key: "heex",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Heex",
	},
	{Key: "hh",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Hh",
	},
	{Key: "hpp",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Hpp",
	},
	{Key: "hrl",
		Icon:        "",
		Color:       "#B83998",
		Cterm_color: "163",
		Name:        "Hrl",
	},
	{Key: "hs",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Hs",
	},
	{Key: "http",
		Icon:        "",
		Color:       "#008ec7",
		Cterm_color: "31",
		Name:        "HTTP",
	},
	{Key: "htm",
		Icon:        "",
		Color:       "#e34c26",
		Cterm_color: "196",
		Name:        "Htm",
	},
	{Key: "html",
		Icon:        "",
		Color:       "#e44d26",
		Cterm_color: "196",
		Name:        "Html",
	},
	{Key: "huff",
		Icon:        "󰡘",
		Color:       "#4242c7",
		Cterm_color: "56",
		Name:        "Huff",
	},
	{Key: "hurl",
		Icon:        "",
		Color:       "#ff0288",
		Cterm_color: "198",
		Name:        "Hurl",
	},
	{Key: "hxx",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Hxx",
	},
	{Key: "ixx",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Ixx",
	},
	{Key: "ico",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Ico",
	},
	{Key: "ical",
		Icon:        "",
		Color:       "#2B2e83",
		Cterm_color: "18",
		Name:        "Ical",
	},
	{Key: "icalendar",
		Icon:        "",
		Color:       "#2B2e83",
		Cterm_color: "18",
		Name:        "Icalendar",
	},
	{Key: "ics",
		Icon:        "",
		Color:       "#2B2e83",
		Cterm_color: "18",
		Name:        "Ics",
	},
	{Key: "ifb",
		Icon:        "",
		Color:       "#2B2e83",
		Cterm_color: "18",
		Name:        "Ifb",
	},
	{Key: "ifc",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "Ifc",
	},
	{Key: "ige",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "Ige",
	},
	{Key: "iges",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "Iges",
	},
	{Key: "igs",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "Igs",
	},
	{Key: "image",
		Icon:        "",
		Color:       "#d0bec8",
		Cterm_color: "181",
		Name:        "Image",
	},
	{Key: "img",
		Icon:        "",
		Color:       "#d0bec8",
		Cterm_color: "181",
		Name:        "Img",
	},
	{Key: "import",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "ImportConfiguration",
	},
	{Key: "info",
		Icon:        "",
		Color:       "#ffffcd",
		Cterm_color: "230",
		Name:        "Info",
	},
	{Key: "ini",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Ini",
	},
	{Key: "ino",
		Icon:        "",
		Color:       "#56b6c2",
		Cterm_color: "73",
		Name:        "Arduino",
	},
	{Key: "iso",
		Icon:        "",
		Color:       "#d0bec8",
		Cterm_color: "181",
		Name:        "Iso",
	},
	{Key: "ipynb",
		Icon:        "",
		Color:       "#51a0cf",
		Cterm_color: "74",
		Name:        "Notebook",
	},
	{Key: "java",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "Java",
	},
	{Key: "jl",
		Icon:        "",
		Color:       "#a270ba",
		Cterm_color: "133",
		Name:        "Jl",
	},
	{Key: "jwmrc",
		Icon:        "",
		Color:       "#0078cd",
		Cterm_color: "32",
		Name:        "JWM",
	},
	{Key: "jpeg",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Jpeg",
	},
	{Key: "jpg",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Jpg",
	},
	{Key: "js",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Js",
	},
	{Key: "json",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Json",
	},
	{Key: "json5",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Json5",
	},
	{Key: "jsonc",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "Jsonc",
	},
	{Key: "jsx",
		Icon:        "",
		Color:       "#20c2e3",
		Cterm_color: "45",
		Name:        "Jsx",
	},
	{Key: "jxl",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "JpegXl",
	},
	{Key: "kbx",
		Icon:        "󰯄",
		Color:       "#737672",
		Cterm_color: "243",
		Name:        "Kbx",
	},
	{Key: "kdb",
		Icon:        "",
		Color:       "#529b34",
		Cterm_color: "71",
		Name:        "Kdb",
	},
	{Key: "kdbx",
		Icon:        "",
		Color:       "#529b34",
		Cterm_color: "71",
		Name:        "Kdbx",
	},
	{Key: "kdenlive",
		Icon:        "",
		Color:       "#83b8f2",
		Cterm_color: "110",
		Name:        "Kdenlive",
	},
	{Key: "kdenlivetitle",
		Icon:        "",
		Color:       "#83b8f2",
		Cterm_color: "110",
		Name:        "Kdenlive",
	},
	{Key: "kicad_dru",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCad",
	},
	{Key: "kicad_mod",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCad",
	},
	{Key: "kicad_pcb",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCad",
	},
	{Key: "kicad_prl",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCad",
	},
	{Key: "kicad_pro",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCad",
	},
	{Key: "kicad_sch",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCad",
	},
	{Key: "kicad_sym",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCad",
	},
	{Key: "kicad_wks",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "KiCad",
	},
	{Key: "ko",
		Icon:        "",
		Color:       "#dcddd6",
		Cterm_color: "253",
		Name:        "LinuxKernelObject",
	},
	{Key: "kpp",
		Icon:        "",
		Color:       "#f245fb",
		Cterm_color: "201",
		Name:        "Krita",
	},
	{Key: "kra",
		Icon:        "",
		Color:       "#f245fb",
		Cterm_color: "201",
		Name:        "Krita",
	},
	{Key: "krz",
		Icon:        "",
		Color:       "#f245fb",
		Cterm_color: "201",
		Name:        "Krita",
	},
	{Key: "ksh",
		Icon:        "",
		Color:       "#4d5a5e",
		Cterm_color: "240",
		Name:        "Ksh",
	},
	{Key: "kt",
		Icon:        "",
		Color:       "#7F52FF",
		Cterm_color: "99",
		Name:        "Kotlin",
	},
	{Key: "kts",
		Icon:        "",
		Color:       "#7F52FF",
		Cterm_color: "99",
		Name:        "KotlinScript",
	},
	{Key: "lck",
		Icon:        "",
		Color:       "#bbbbbb",
		Cterm_color: "250",
		Name:        "Lock",
	},
	{Key: "leex",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Leex",
	},
	{Key: "less",
		Icon:        "",
		Color:       "#563d7c",
		Cterm_color: "54",
		Name:        "Less",
	},
	{Key: "lff",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "LibrecadFontFile",
	},
	{Key: "lhs",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Lhs",
	},
	{Key: "lib",
		Icon:        "",
		Color:       "#4d2c0b",
		Cterm_color: "52",
		Name:        "Lib",
	},
	{Key: "license",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "License",
	},
	{Key: "liquid",
		Icon:        "",
		Color:       "#95BF47",
		Cterm_color: "106",
		Name:        "Liquid",
	},
	{Key: "lock",
		Icon:        "",
		Color:       "#bbbbbb",
		Cterm_color: "250",
		Name:        "Lock",
	},
	{Key: "log",
		Icon:        "󰌱",
		Color:       "#dddddd",
		Cterm_color: "253",
		Name:        "Log",
	},
	{Key: "lrc",
		Icon:        "󰨖",
		Color:       "#ffb713",
		Cterm_color: "214",
		Name:        "Lrc",
	},
	{Key: "lua",
		Icon:        "",
		Color:       "#51a0cf",
		Cterm_color: "74",
		Name:        "Lua",
	},
	{Key: "luac",
		Icon:        "",
		Color:       "#51a0cf",
		Cterm_color: "74",
		Name:        "Lua",
	},
	{Key: "luau",
		Icon:        "",
		Color:       "#00a2ff",
		Cterm_color: "75",
		Name:        "Luau",
	},
	{Key: "m3u",
		Icon:        "󰲹",
		Color:       "#ed95ae",
		Cterm_color: "211",
		Name:        "M3u",
	},
	{Key: "m3u8",
		Icon:        "󰲹",
		Color:       "#ed95ae",
		Cterm_color: "211",
		Name:        "M3u8",
	},
	{Key: "m4a",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "MPEG4",
	},
	{Key: "m4v",
		Icon:        "",
		Color:       "#FD971F",
		Cterm_color: "208",
		Name:        "M4V",
	},
	{Key: "magnet",
		Icon:        "",
		Color:       "#a51b16",
		Cterm_color: "124",
		Name:        "Magnet",
	},
	{Key: "makefile",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Makefile",
	},
	{Key: "markdown",
		Icon:        "",
		Color:       "#dddddd",
		Cterm_color: "253",
		Name:        "Markdown",
	},
	{Key: "material",
		Icon:        "󰔉",
		Color:       "#B83998",
		Cterm_color: "163",
		Name:        "Material",
	},
	{Key: "md",
		Icon:        "",
		Color:       "#dddddd",
		Cterm_color: "253",
		Name:        "Md",
	},
	{Key: "md5",
		Icon:        "󰕥",
		Color:       "#8c86af",
		Cterm_color: "103",
		Name:        "Md5",
	},
	{Key: "mdx",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Mdx",
	},
	{Key: "mint",
		Icon:        "󰌪",
		Color:       "#87c095",
		Cterm_color: "108",
		Name:        "Mint",
	},
	{Key: "mjs",
		Icon:        "",
		Color:       "#f1e05a",
		Cterm_color: "185",
		Name:        "Mjs",
	},
	{Key: "mk",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Makefile",
	},
	{Key: "mkv",
		Icon:        "",
		Color:       "#FD971F",
		Cterm_color: "208",
		Name:        "Mkv",
	},
	{Key: "ml",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Ml",
	},
	{Key: "mli",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Mli",
	},
	{Key: "m",
		Icon:        "",
		Color:       "#599eff",
		Cterm_color: "111",
		Name:        "ObjectiveC",
	},
	{Key: "mm",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "ObjectiveCPlusPlus",
	},
	{Key: "mo",
		Icon:        "∞",
		Color:       "#9772FB",
		Cterm_color: "135",
		Name:        "Motoko",
	},
	{Key: "mobi",
		Icon:        "",
		Color:       "#eab16d",
		Cterm_color: "215",
		Name:        "Mobi",
	},
	{Key: "mojo",
		Icon:        "",
		Color:       "#ff4c1f",
		Cterm_color: "196",
		Name:        "Mojo",
	},
	{Key: "🔥",
		Icon:        "",
		Color:       "#ff4c1f",
		Cterm_color: "196",
		Name:        "Mojo",
	},
	{Key: "mov",
		Icon:        "",
		Color:       "#FD971F",
		Cterm_color: "208",
		Name:        "MOV",
	},
	{Key: "mp3",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "MPEGAudioLayerIII",
	},
	{Key: "mp4",
		Icon:        "",
		Color:       "#FD971F",
		Cterm_color: "208",
		Name:        "Mp4",
	},
	{Key: "mpp",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Mpp",
	},
	{Key: "msf",
		Icon:        "",
		Color:       "#137be1",
		Cterm_color: "33",
		Name:        "Thunderbird",
	},
	{Key: "mts",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Mts",
	},
	{Key: "mustache",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Mustache",
	},
	{Key: "nfo",
		Icon:        "",
		Color:       "#ffffcd",
		Cterm_color: "230",
		Name:        "Nfo",
	},
	{Key: "nim",
		Icon:        "",
		Color:       "#f3d400",
		Cterm_color: "220",
		Name:        "Nim",
	},
	{Key: "nix",
		Icon:        "",
		Color:       "#7ebae4",
		Cterm_color: "110",
		Name:        "Nix",
	},
	{Key: "nswag",
		Icon:        "",
		Color:       "#85ea2d",
		Cterm_color: "112",
		Name:        "Nswag",
	},
	{Key: "nu",
		Icon:        ">",
		Color:       "#3aa675",
		Cterm_color: "36",
		Name:        "Nushell",
	},
	{Key: "o",
		Icon:        "",
		Color:       "#9F0500",
		Cterm_color: "124",
		Name:        "ObjectFile",
	},
	{Key: "obj",
		Icon:        "󰆧",
		Color:       "#888888",
		Cterm_color: "102",
		Name:        "3DObjectFile",
	},
	{Key: "ogg",
		Icon:        "",
		Color:       "#0075aa",
		Cterm_color: "24",
		Name:        "OggVorbis",
	},
	{Key: "opus",
		Icon:        "",
		Color:       "#0075aa",
		Cterm_color: "24",
		Name:        "OpusAudioFile",
	},
	{Key: "org",
		Icon:        "",
		Color:       "#77AA99",
		Cterm_color: "73",
		Name:        "OrgMode",
	},
	{Key: "otf",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "OpenTypeFont",
	},
	{Key: "out",
		Icon:        "",
		Color:       "#9F0500",
		Cterm_color: "124",
		Name:        "Out",
	},
	{Key: "part",
		Icon:        "",
		Color:       "#44cda8",
		Cterm_color: "43",
		Name:        "Part",
	},
	{Key: "patch",
		Icon:        "",
		Color:       "#41535b",
		Cterm_color: "239",
		Name:        "Patch",
	},
	{Key: "pck",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "PackedResource",
	},
	{Key: "pcm",
		Icon:        "",
		Color:       "#0075aa",
		Cterm_color: "24",
		Name:        "PulseCodeModulation",
	},
	{Key: "pdf",
		Icon:        "",
		Color:       "#b30b00",
		Cterm_color: "124",
		Name:        "Pdf",
	},
	{Key: "php",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Php",
	},
	{Key: "pl",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Pl",
	},
	{Key: "pls",
		Icon:        "󰲹",
		Color:       "#ed95ae",
		Cterm_color: "211",
		Name:        "Pls",
	},
	{Key: "ply",
		Icon:        "󰆧",
		Color:       "#888888",
		Cterm_color: "102",
		Name:        "3DObjectFile",
	},
	{Key: "pm",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Pm",
	},
	{Key: "png",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Png",
	},
	{Key: "po",
		Icon:        "",
		Color:       "#2596be",
		Cterm_color: "31",
		Name:        "Localization",
	},
	{Key: "pot",
		Icon:        "",
		Color:       "#2596be",
		Cterm_color: "31",
		Name:        "Localization",
	},
	{Key: "pp",
		Icon:        "",
		Color:       "#FFA61A",
		Cterm_color: "214",
		Name:        "Pp",
	},
	{Key: "ppt",
		Icon:        "󰈧",
		Color:       "#cb4a32",
		Cterm_color: "160",
		Name:        "Ppt",
	},
	{Key: "prisma",
		Icon:        "",
		Color:       "#5a67d8",
		Cterm_color: "62",
		Name:        "Prisma",
	},
	{Key: "pro",
		Icon:        "",
		Color:       "#e4b854",
		Cterm_color: "179",
		Name:        "Prolog",
	},
	{Key: "ps1",
		Icon:        "󰨊",
		Color:       "#4273ca",
		Cterm_color: "68",
		Name:        "PsScriptfile",
	},
	{Key: "psd1",
		Icon:        "󰨊",
		Color:       "#6975c4",
		Cterm_color: "68",
		Name:        "PsManifestfile",
	},
	{Key: "psm1",
		Icon:        "󰨊",
		Color:       "#6975c4",
		Cterm_color: "68",
		Name:        "PsScriptModulefile",
	},
	{Key: "psb",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Psb",
	},
	{Key: "psd",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Psd",
	},
	{Key: "pub",
		Icon:        "󰷖",
		Color:       "#e3c58e",
		Cterm_color: "222",
		Name:        "Pub",
	},
	{Key: "pxd",
		Icon:        "",
		Color:       "#5aa7e4",
		Cterm_color: "39",
		Name:        "Pxd",
	},
	{Key: "pxi",
		Icon:        "",
		Color:       "#5aa7e4",
		Cterm_color: "39",
		Name:        "Pxi",
	},
	{Key: "py",
		Icon:        "",
		Color:       "#ffbc03",
		Cterm_color: "214",
		Name:        "Py",
	},
	{Key: "pyc",
		Icon:        "",
		Color:       "#ffe291",
		Cterm_color: "222",
		Name:        "Pyc",
	},
	{Key: "pyd",
		Icon:        "",
		Color:       "#ffe291",
		Cterm_color: "222",
		Name:        "Pyd",
	},
	{Key: "pyi",
		Icon:        "",
		Color:       "#ffbc03",
		Cterm_color: "214",
		Name:        "Pyi",
	},
	{Key: "pyo",
		Icon:        "",
		Color:       "#ffe291",
		Cterm_color: "222",
		Name:        "Pyo",
	},
	{Key: "pyw",
		Icon:        "",
		Color:       "#5aa7e4",
		Cterm_color: "39",
		Name:        "Pyw",
	},
	{Key: "pyx",
		Icon:        "",
		Color:       "#5aa7e4",
		Cterm_color: "39",
		Name:        "Pyx",
	},
	{Key: "qm",
		Icon:        "",
		Color:       "#2596be",
		Cterm_color: "31",
		Name:        "Localization",
	},
	{Key: "qml",
		Icon:        "",
		Color:       "#40cd52",
		Cterm_color: "77",
		Name:        "Qt",
	},
	{Key: "qrc",
		Icon:        "",
		Color:       "#40cd52",
		Cterm_color: "77",
		Name:        "Qt",
	},
	{Key: "qss",
		Icon:        "",
		Color:       "#40cd52",
		Cterm_color: "77",
		Name:        "Qt",
	},
	{Key: "query",
		Icon:        "",
		Color:       "#90a850",
		Cterm_color: "107",
		Name:        "Query",
	},
	{Key: "r",
		Icon:        "󰟔",
		Color:       "#2266ba",
		Cterm_color: "25",
		Name:        "R",
	},
	{Key: "rake",
		Icon:        "",
		Color:       "#701516",
		Cterm_color: "52",
		Name:        "Rake",
	},
	{Key: "rar",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Rar",
	},
	{Key: "razor",
		Icon:        "󱦘",
		Color:       "#512bd4",
		Cterm_color: "56",
		Name:        "RazorPage",
	},
	{Key: "rb",
		Icon:        "",
		Color:       "#701516",
		Cterm_color: "52",
		Name:        "Rb",
	},
	{Key: "res",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "ReScript",
	},
	{Key: "resi",
		Icon:        "",
		Color:       "#f55385",
		Cterm_color: "204",
		Name:        "ReScriptInterface",
	},
	{Key: "rlib",
		Icon:        "",
		Color:       "#dea584",
		Cterm_color: "216",
		Name:        "Rlib",
	},
	{Key: "rmd",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Rmd",
	},
	{Key: "rproj",
		Icon:        "󰗆",
		Color:       "#358a5b",
		Cterm_color: "29",
		Name:        "Rproj",
	},
	{Key: "rs",
		Icon:        "",
		Color:       "#dea584",
		Cterm_color: "216",
		Name:        "Rs",
	},
	{Key: "rss",
		Icon:        "",
		Color:       "#FB9D3B",
		Cterm_color: "215",
		Name:        "Rss",
	},
	{Key: "sass",
		Icon:        "",
		Color:       "#f55385",
		Cterm_color: "204",
		Name:        "Sass",
	},
	{Key: "sbt",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "sbt",
	},
	{Key: "scad",
		Icon:        "",
		Color:       "#f9d72c",
		Cterm_color: "220",
		Name:        "OpenSCAD",
	},
	{Key: "scala",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "Scala",
	},
	{Key: "sc",
		Icon:        "",
		Color:       "#cc3e44",
		Cterm_color: "167",
		Name:        "ScalaScript",
	},
	{Key: "scm",
		Icon:        "󰘧",
		Color:       "#eeeeee",
		Cterm_color: "255",
		Name:        "Scheme",
	},
	{Key: "scss",
		Icon:        "",
		Color:       "#f55385",
		Cterm_color: "204",
		Name:        "Scss",
	},
	{Key: "sh",
		Icon:        "",
		Color:       "#4d5a5e",
		Cterm_color: "240",
		Name:        "Sh",
	},
	{Key: "sha1",
		Icon:        "󰕥",
		Color:       "#8c86af",
		Cterm_color: "103",
		Name:        "Sha1",
	},
	{Key: "sha224",
		Icon:        "󰕥",
		Color:       "#8c86af",
		Cterm_color: "103",
		Name:        "Sha224",
	},
	{Key: "sha256",
		Icon:        "󰕥",
		Color:       "#8c86af",
		Cterm_color: "103",
		Name:        "Sha256",
	},
	{Key: "sha384",
		Icon:        "󰕥",
		Color:       "#8c86af",
		Cterm_color: "103",
		Name:        "Sha384",
	},
	{Key: "sha512",
		Icon:        "󰕥",
		Color:       "#8c86af",
		Cterm_color: "103",
		Name:        "Sha512",
	},
	{Key: "sig",
		Icon:        "λ",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Sig",
	},
	{Key: "signature",
		Icon:        "λ",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Signature",
	},
	{Key: "skp",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "SketchUp",
	},
	{Key: "sldasm",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "SolidWorksAsm",
	},
	{Key: "sldprt",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "SolidWorksPrt",
	},
	{Key: "slim",
		Icon:        "",
		Color:       "#e34c26",
		Cterm_color: "196",
		Name:        "Slim",
	},
	{Key: "sln",
		Icon:        "",
		Color:       "#854CC7",
		Cterm_color: "98",
		Name:        "Sln",
	},
	{Key: "slvs",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "SolveSpace",
	},
	{Key: "sml",
		Icon:        "λ",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Sml",
	},
	{Key: "so",
		Icon:        "",
		Color:       "#dcddd6",
		Cterm_color: "253",
		Name:        "SharedObject",
	},
	{Key: "sol",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Solidity",
	},
	{Key: "spec.js",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "SpecJs",
	},
	{Key: "spec.jsx",
		Icon:        "",
		Color:       "#20c2e3",
		Cterm_color: "45",
		Name:        "JavaScriptReactSpec",
	},
	{Key: "spec.ts",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "SpecTs",
	},
	{Key: "spec.tsx",
		Icon:        "",
		Color:       "#1354bf",
		Cterm_color: "26",
		Name:        "TypeScriptReactSpec",
	},
	{Key: "sql",
		Icon:        "",
		Color:       "#dad8d8",
		Cterm_color: "188",
		Name:        "Sql",
	},
	{Key: "sqlite",
		Icon:        "",
		Color:       "#dad8d8",
		Cterm_color: "188",
		Name:        "Sql",
	},
	{Key: "sqlite3",
		Icon:        "",
		Color:       "#dad8d8",
		Cterm_color: "188",
		Name:        "Sql",
	},
	{Key: "srt",
		Icon:        "󰨖",
		Color:       "#ffb713",
		Cterm_color: "214",
		Name:        "Srt",
	},
	{Key: "ssa",
		Icon:        "󰨖",
		Color:       "#ffb713",
		Cterm_color: "214",
		Name:        "Ssa",
	},
	{Key: "stl",
		Icon:        "󰆧",
		Color:       "#888888",
		Cterm_color: "102",
		Name:        "3DObjectFile",
	},
	{Key: "strings",
		Icon:        "",
		Color:       "#2596be",
		Cterm_color: "31",
		Name:        "Localization",
	},
	{Key: "ste",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "Ste",
	},
	{Key: "step",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "Step",
	},
	{Key: "stp",
		Icon:        "󰻫",
		Color:       "#839463",
		Cterm_color: "101",
		Name:        "Stp",
	},
	{Key: "styl",
		Icon:        "",
		Color:       "#8dc149",
		Cterm_color: "113",
		Name:        "Styl",
	},
	{Key: "sub",
		Icon:        "󰨖",
		Color:       "#ffb713",
		Cterm_color: "214",
		Name:        "Sub",
	},
	{Key: "sublime",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Sublime",
	},
	{Key: "suo",
		Icon:        "",
		Color:       "#854CC7",
		Cterm_color: "98",
		Name:        "Suo",
	},
	{Key: "sv",
		Icon:        "󰍛",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "SystemVerilog",
	},
	{Key: "svelte",
		Icon:        "",
		Color:       "#ff3e00",
		Cterm_color: "196",
		Name:        "Svelte",
	},
	{Key: "svh",
		Icon:        "󰍛",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "SystemVerilog",
	},
	{Key: "svg",
		Icon:        "󰜡",
		Color:       "#FFB13B",
		Cterm_color: "214",
		Name:        "Svg",
	},
	{Key: "swift",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Swift",
	},
	{Key: "t",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Tor",
	},
	{Key: "tbc",
		Icon:        "󰛓",
		Color:       "#1e5cb3",
		Cterm_color: "25",
		Name:        "Tcl",
	},
	{Key: "tcl",
		Icon:        "󰛓",
		Color:       "#1e5cb3",
		Cterm_color: "25",
		Name:        "Tcl",
	},
	{Key: "templ",
		Icon:        "",
		Color:       "#dbbd30",
		Cterm_color: "178",
		Name:        "Templ",
	},
	{Key: "terminal",
		Icon:        "",
		Color:       "#31B53E",
		Cterm_color: "34",
		Name:        "Terminal",
	},
	{Key: "test.js",
		Icon:        "",
		Color:       "#cbcb41",
		Cterm_color: "185",
		Name:        "TestJs",
	},
	{Key: "test.jsx",
		Icon:        "",
		Color:       "#20c2e3",
		Cterm_color: "45",
		Name:        "JavaScriptReactTest",
	},
	{Key: "test.ts",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "TestTs",
	},
	{Key: "test.tsx",
		Icon:        "",
		Color:       "#1354bf",
		Cterm_color: "26",
		Name:        "TypeScriptReactTest",
	},
	{Key: "tex",
		Icon:        "",
		Color:       "#3D6117",
		Cterm_color: "22",
		Name:        "Tex",
	},
	{Key: "tf",
		Icon:        "",
		Color:       "#5F43E9",
		Cterm_color: "93",
		Name:        "Terraform",
	},
	{Key: "tfvars",
		Icon:        "",
		Color:       "#5F43E9",
		Cterm_color: "93",
		Name:        "TFVars",
	},
	{Key: "tgz",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Tgz",
	},
	{Key: "tmux",
		Icon:        "",
		Color:       "#14ba19",
		Cterm_color: "34",
		Name:        "Tmux",
	},
	{Key: "toml",
		Icon:        "",
		Color:       "#9c4221",
		Cterm_color: "124",
		Name:        "Toml",
	},
	{Key: "torrent",
		Icon:        "",
		Color:       "#44cda8",
		Cterm_color: "43",
		Name:        "Torrent",
	},
	{Key: "tres",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "GodotTextResource",
	},
	{Key: "ts",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "TypeScript",
	},
	{Key: "tscn",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "GodotTextScene",
	},
	{Key: "tsconfig",
		Icon:        "",
		Color:       "#FF8700",
		Cterm_color: "208",
		Name:        "TypoScriptConfig",
	},
	{Key: "tsx",
		Icon:        "",
		Color:       "#1354bf",
		Cterm_color: "26",
		Name:        "Tsx",
	},
	{Key: "ttf",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "TrueTypeFont",
	},
	{Key: "twig",
		Icon:        "",
		Color:       "#8dc149",
		Cterm_color: "113",
		Name:        "Twig",
	},
	{Key: "txz",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Txz",
	},
	{Key: "typoscript",
		Icon:        "",
		Color:       "#FF8700",
		Cterm_color: "208",
		Name:        "TypoScript",
	},
	{Key: "txt",
		Icon:        "󰈙",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Txt",
	},
	{Key: "ui",
		Icon:        "",
		Color:       "#015BF0",
		Cterm_color: "27",
		Name:        "UI",
	},
	{Key: "v",
		Icon:        "󰍛",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "Verilog",
	},
	{Key: "vala",
		Icon:        "",
		Color:       "#7239b3",
		Cterm_color: "91",
		Name:        "Vala",
	},
	{Key: "vh",
		Icon:        "󰍛",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "Verilog",
	},
	{Key: "vhd",
		Icon:        "󰍛",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "VHDL",
	},
	{Key: "vhdl",
		Icon:        "󰍛",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "VHDL",
	},
	{Key: "vim",
		Icon:        "",
		Color:       "#019833",
		Cterm_color: "28",
		Name:        "Vim",
	},
	{Key: "vsh",
		Icon:        "",
		Color:       "#5d87bf",
		Cterm_color: "67",
		Name:        "Vlang",
	},
	{Key: "vsix",
		Icon:        "",
		Color:       "#854CC7",
		Cterm_color: "98",
		Name:        "Vsix",
	},
	{Key: "vue",
		Icon:        "",
		Color:       "#8dc149",
		Cterm_color: "113",
		Name:        "Vue",
	},
	{Key: "wasm",
		Icon:        "",
		Color:       "#5c4cdb",
		Cterm_color: "62",
		Name:        "Wasm",
	},
	{Key: "wav",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "WaveformAudioFile",
	},
	{Key: "webm",
		Icon:        "",
		Color:       "#FD971F",
		Cterm_color: "208",
		Name:        "Webm",
	},
	{Key: "webmanifest",
		Icon:        "",
		Color:       "#f1e05a",
		Cterm_color: "185",
		Name:        "Webmanifest",
	},
	{Key: "webp",
		Icon:        "",
		Color:       "#a074c4",
		Cterm_color: "140",
		Name:        "Webp",
	},
	{Key: "webpack",
		Icon:        "󰜫",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Webpack",
	},
	{Key: "wma",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "WindowsMediaAudio",
	},
	{Key: "woff",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "WebOpenFontFormat",
	},
	{Key: "woff2",
		Icon:        "",
		Color:       "#ECECEC",
		Cterm_color: "255",
		Name:        "WebOpenFontFormat",
	},
	{Key: "wrl",
		Icon:        "󰆧",
		Color:       "#888888",
		Cterm_color: "102",
		Name:        "VRML",
	},
	{Key: "wrz",
		Icon:        "󰆧",
		Color:       "#888888",
		Cterm_color: "102",
		Name:        "VRML",
	},
	{Key: "wv",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "WavPack",
	},
	{Key: "wvc",
		Icon:        "",
		Color:       "#00afff",
		Cterm_color: "39",
		Name:        "WavPackCorrection",
	},
	{Key: "x",
		Icon:        "",
		Color:       "#599eff",
		Cterm_color: "111",
		Name:        "Logos",
	},
	{Key: "xm",
		Icon:        "",
		Color:       "#519aba",
		Cterm_color: "74",
		Name:        "Logos",
	},
	{Key: "xaml",
		Icon:        "󰙳",
		Color:       "#512bd4",
		Cterm_color: "56",
		Name:        "Xaml",
	},
	{Key: "xcf",
		Icon:        "",
		Color:       "#635b46",
		Cterm_color: "240",
		Name:        "GIMP",
	},
	{Key: "xcplayground",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "XcPlayground",
	},
	{Key: "xcstrings",
		Icon:        "",
		Color:       "#2596be",
		Cterm_color: "31",
		Name:        "XcLocalization",
	},
	{Key: "xls",
		Icon:        "󰈛",
		Color:       "#207245",
		Cterm_color: "29",
		Name:        "Xls",
	},
	{Key: "xlsx",
		Icon:        "󰈛",
		Color:       "#207245",
		Cterm_color: "29",
		Name:        "Xlsx",
	},
	{Key: "xml",
		Icon:        "󰗀",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Xml",
	},
	{Key: "xpi",
		Icon:        "",
		Color:       "#ff1b01",
		Cterm_color: "196",
		Name:        "Xpi",
	},
	{Key: "xul",
		Icon:        "",
		Color:       "#e37933",
		Cterm_color: "166",
		Name:        "Xul",
	},
	{Key: "xz",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Xz",
	},
	{Key: "yaml",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Yaml",
	},
	{Key: "yml",
		Icon:        "",
		Color:       "#6d8086",
		Cterm_color: "66",
		Name:        "Yml",
	},
	{Key: "zig",
		Icon:        "",
		Color:       "#f69a1b",
		Cterm_color: "172",
		Name:        "Zig",
	},
	{Key: "zip",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Zip",
	},
	{Key: "zsh",
		Icon:        "",
		Color:       "#89e051",
		Cterm_color: "113",
		Name:        "Zsh",
	},
	{Key: "zst",
		Icon:        "",
		Color:       "#eca517",
		Cterm_color: "214",
		Name:        "Zst",
	},
}

var icons_by_operating_system = []Icon{
	{Key: "apple",
		Icon:        "",
		Color:       "#A2AAAD",
		Cterm_color: "248",
		Name:        "Apple",
	},
	{Key: "windows",
		Icon:        "",
		Color:       "#00A4EF",
		Cterm_color: "39",
		Name:        "Windows",
	},
	{Key: "linux",
		Icon:        "",
		Color:       "#fdfdfb",
		Cterm_color: "231",
		Name:        "Linux",
	},
	{Key: "alma",
		Icon:        "",
		Color:       "#ff4649",
		Cterm_color: "203",
		Name:        "Almalinux",
	},
	{Key: "alpine",
		Icon:        "",
		Color:       "#0d597f",
		Cterm_color: "24",
		Name:        "Alpine",
	},
	{Key: "aosc",
		Icon:        "",
		Color:       "#c00000",
		Cterm_color: "124",
		Name:        "AOSC",
	},
	{Key: "arch",
		Icon:        "󰣇",
		Color:       "#0f94d2",
		Cterm_color: "67",
		Name:        "Arch",
	},
	{Key: "archcraft",
		Icon:        "",
		Color:       "#86bba3",
		Cterm_color: "108",
		Name:        "Archcraft",
	},
	{Key: "archlabs",
		Icon:        "",
		Color:       "#503f42",
		Cterm_color: "238",
		Name:        "Archlabs",
	},
	{Key: "arcolinux",
		Icon:        "",
		Color:       "#6690eb",
		Cterm_color: "68",
		Name:        "ArcoLinux",
	},
	{Key: "artix",
		Icon:        "",
		Color:       "#41b4d7",
		Cterm_color: "38",
		Name:        "Artix",
	},
	{Key: "biglinux",
		Icon:        "",
		Color:       "#189fc8",
		Cterm_color: "38",
		Name:        "BigLinux",
	},
	{Key: "centos",
		Icon:        "",
		Color:       "#a2518d",
		Cterm_color: "132",
		Name:        "Centos",
	},
	{Key: "crystallinux",
		Icon:        "",
		Color:       "#a900ff",
		Cterm_color: "129",
		Name:        "CrystalLinux",
	},
	{Key: "debian",
		Icon:        "",
		Color:       "#a80030",
		Cterm_color: "88",
		Name:        "Debian",
	},
	{Key: "deepin",
		Icon:        "",
		Color:       "#2ca7f8",
		Cterm_color: "39",
		Name:        "Deepin",
	},
	{Key: "devuan",
		Icon:        "",
		Color:       "#404a52",
		Cterm_color: "238",
		Name:        "Devuan",
	},
	{Key: "elementary",
		Icon:        "",
		Color:       "#5890c2",
		Cterm_color: "67",
		Name:        "Elementary",
	},
	{Key: "endeavour",
		Icon:        "",
		Color:       "#7b3db9",
		Cterm_color: "91",
		Name:        "Endeavour",
	},
	{Key: "fedora",
		Icon:        "",
		Color:       "#072a5e",
		Cterm_color: "17",
		Name:        "Fedora",
	},
	{Key: "freebsd",
		Icon:        "",
		Color:       "#c90f02",
		Cterm_color: "160",
		Name:        "FreeBSD",
	},
	{Key: "garuda",
		Icon:        "",
		Color:       "#2974e1",
		Cterm_color: "33",
		Name:        "GarudaLinux",
	},
	{Key: "gentoo",
		Icon:        "󰣨",
		Color:       "#b1abce",
		Cterm_color: "146",
		Name:        "Gentoo",
	},
	{Key: "guix",
		Icon:        "",
		Color:       "#ffcc00",
		Cterm_color: "220",
		Name:        "Guix",
	},
	{Key: "hyperbola",
		Icon:        "",
		Color:       "#c0c0c0",
		Cterm_color: "250",
		Name:        "HyperbolaGNULinuxLibre",
	},
	{Key: "illumos",
		Icon:        "",
		Color:       "#ff430f",
		Cterm_color: "196",
		Name:        "Illumos",
	},
	{Key: "kali",
		Icon:        "",
		Color:       "#2777ff",
		Cterm_color: "69",
		Name:        "Kali",
	},
	{Key: "kdeneon",
		Icon:        "",
		Color:       "#20a6a4",
		Cterm_color: "37",
		Name:        "KDEneon",
	},
	{Key: "kubuntu",
		Icon:        "",
		Color:       "#007ac2",
		Cterm_color: "32",
		Name:        "Kubuntu",
	},
	{Key: "locos",
		Icon:        "",
		Color:       "#fab402",
		Cterm_color: "214",
		Name:        "LocOS",
	},
	{Key: "lxle",
		Icon:        "",
		Color:       "#474747",
		Cterm_color: "238",
		Name:        "LXLE",
	},
	{Key: "mageia",
		Icon:        "",
		Color:       "#2397d4",
		Cterm_color: "67",
		Name:        "Mageia",
	},
	{Key: "manjaro",
		Icon:        "",
		Color:       "#33b959",
		Cterm_color: "35",
		Name:        "Manjaro",
	},
	{Key: "mint",
		Icon:        "󰣭",
		Color:       "#66af3d",
		Cterm_color: "70",
		Name:        "Mint",
	},
	{Key: "mxlinux",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "MXLinux",
	},
	{Key: "nixos",
		Icon:        "",
		Color:       "#7ab1db",
		Cterm_color: "110",
		Name:        "NixOS",
	},
	{Key: "openbsd",
		Icon:        "",
		Color:       "#f2ca30",
		Cterm_color: "220",
		Name:        "OpenBSD",
	},
	{Key: "opensuse",
		Icon:        "",
		Color:       "#6fb424",
		Cterm_color: "70",
		Name:        "openSUSE",
	},
	{Key: "parabola",
		Icon:        "",
		Color:       "#797dac",
		Cterm_color: "103",
		Name:        "ParabolaGNULinuxLibre",
	},
	{Key: "parrot",
		Icon:        "",
		Color:       "#54deff",
		Cterm_color: "45",
		Name:        "Parrot",
	},
	{Key: "pop_os",
		Icon:        "",
		Color:       "#48b9c7",
		Cterm_color: "73",
		Name:        "Pop_OS",
	},
	{Key: "postmarketos",
		Icon:        "",
		Color:       "#009900",
		Cterm_color: "28",
		Name:        "postmarketOS",
	},
	{Key: "puppylinux",
		Icon:        "",
		Color:       "#a2aeb9",
		Cterm_color: "145",
		Name:        "PuppyLinux",
	},
	{Key: "qubesos",
		Icon:        "",
		Color:       "#3774d8",
		Cterm_color: "33",
		Name:        "QubesOS",
	},
	{Key: "raspberry_pi",
		Icon:        "",
		Color:       "#be1848",
		Cterm_color: "161",
		Name:        "RaspberryPiOS",
	},
	{Key: "redhat",
		Icon:        "󱄛",
		Color:       "#EE0000",
		Cterm_color: "196",
		Name:        "Redhat",
	},
	{Key: "rocky",
		Icon:        "",
		Color:       "#0fb37d",
		Cterm_color: "36",
		Name:        "RockyLinux",
	},
	{Key: "sabayon",
		Icon:        "",
		Color:       "#c6c6c6",
		Cterm_color: "251",
		Name:        "Sabayon",
	},
	{Key: "slackware",
		Icon:        "",
		Color:       "#475fa9",
		Cterm_color: "61",
		Name:        "Slackware",
	},
	{Key: "solus",
		Icon:        "",
		Color:       "#4b5163",
		Cterm_color: "239",
		Name:        "Solus",
	},
	{Key: "tails",
		Icon:        "",
		Color:       "#56347c",
		Cterm_color: "54",
		Name:        "Tails",
	},
	{Key: "trisquel",
		Icon:        "",
		Color:       "#0f58b6",
		Cterm_color: "25",
		Name:        "TrisquelGNULinux",
	},
	{Key: "ubuntu",
		Icon:        "",
		Color:       "#dd4814",
		Cterm_color: "196",
		Name:        "Ubuntu",
	},
	{Key: "vanillaos",
		Icon:        "",
		Color:       "#fabd4d",
		Cterm_color: "214",
		Name:        "VanillaOS",
	},
	{Key: "void",
		Icon:        "",
		Color:       "#295340",
		Cterm_color: "23",
		Name:        "Void",
	},
	{Key: "xerolinux",
		Icon:        "",
		Color:       "#888fe2",
		Cterm_color: "104",
		Name:        "XeroLinux",
	},
	{Key: "zorin",
		Icon:        "",
		Color:       "#14a1e8",
		Cterm_color: "39",
		Name:        "Zorin",
	},
}

var icons_by_desktop_environment = []Icon{
	{Key: "budgie",
		Icon:        "",
		Color:       "#4e5361",
		Cterm_color: "240",
		Name:        "Budgie",
	},
	{Key: "cinnamon",
		Icon:        "",
		Color:       "#dc682e",
		Cterm_color: "166",
		Name:        "Cinnamon",
	},
	{Key: "gnome",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "GNOME",
	},
	{Key: "lxde",
		Icon:        "",
		Color:       "#a4a4a4",
		Cterm_color: "248",
		Name:        "LXDE",
	},
	{Key: "lxqt",
		Icon:        "",
		Color:       "#0191d2",
		Cterm_color: "32",
		Name:        "LXQt",
	},
	{Key: "mate",
		Icon:        "",
		Color:       "#9bda5c",
		Cterm_color: "113",
		Name:        "MATE",
	},
	{Key: "plasma",
		Icon:        "",
		Color:       "#1b89f4",
		Cterm_color: "33",
		Name:        "KDEPlasma",
	},
	{Key: "xfce",
		Icon:        "",
		Color:       "#00aadf",
		Cterm_color: "74",
		Name:        "Xfce",
	},
}

var icons_by_window_manager = []Icon{
	{Key: "awesomewm",
		Icon:        "",
		Color:       "#535d6c",
		Cterm_color: "59",
		Name:        "awesome",
	},
	{Key: "bspwm",
		Icon:        "",
		Color:       "#4f4f4f",
		Cterm_color: "239",
		Name:        "BSPWM",
	},
	{Key: "dwm",
		Icon:        "",
		Color:       "#1177aa",
		Cterm_color: "31",
		Name:        "dwm",
	},
	{Key: "enlightenment",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "Enlightenment",
	},
	{Key: "fluxbox",
		Icon:        "",
		Color:       "#555555",
		Cterm_color: "240",
		Name:        "Fluxbox",
	},
	{Key: "hyprland",
		Icon:        "",
		Color:       "#00aaae",
		Cterm_color: "37",
		Name:        "Hyprland",
	},
	{Key: "i3",
		Icon:        "",
		Color:       "#e8ebee",
		Cterm_color: "255",
		Name:        "i3",
	},
	{Key: "jwm",
		Icon:        "",
		Color:       "#0078cd",
		Cterm_color: "32",
		Name:        "JWM",
	},
	{Key: "qtile",
		Icon:        "",
		Color:       "#ffffff",
		Cterm_color: "231",
		Name:        "Qtile",
	},
	{Key: "sway",
		Icon:        "",
		Color:       "#68751c",
		Cterm_color: "64",
		Name:        "Sway",
	},
	{Key: "xmonad",
		Icon:        "",
		Color:       "#fd4d5d",
		Cterm_color: "203",
		Name:        "xmonad",
	},
}
