colorscheme: edge
wrap: false
lsp:
  c:
    cmd: ""
    log: ""
    args: []
  go:
    cmd: ""
    log: ""
    args: []
  py:
    cmd: ""
    log: ""
    args: []
  java:
    cmd: ""
    log: ""
    args: []
  swift:
    cmd: ""
    log: ""
    args: ["--default-workspace-type","buildServer"]
    # - -Xswiftc
    # - -sdk
    # - -Xswiftc
    # - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk
    # - -Xswiftc
    # - -target
    # - -Xswiftc
    # - arm64-apple-ios13.0-simulator
    # - -Xcc
    # - -DSWIFT_PACKAGE=0
  javascript:
    cmd: ""
    log: ""
    args: []
  typescript:
    cmd: ""
    log: ""
    args: []
color: {}
vim:
  leadkey: space
  enable: false 
keyboard: {}
