---
name: Crosscompile

"on":
  push:
    branches:
      - master

jobs:
  test:
    name: Run ./test_crosscompile.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ./test_crosscompile.sh
        run: ./test_crosscompile.sh
