package lspcore


// LanguageIdentifier represents the language identifiers.
type LanguageIdentifier string

const (
	BAT           LanguageIdentifier = "bat"
	BIBTEX        LanguageIdentifier = "bibtex"
	CLOJURE       LanguageIdentifier = "clojure"
	COFFEESCRIPT  LanguageIdentifier = "coffeescript"
	C             LanguageIdentifier = "c"
	CPP           LanguageIdentifier = "cpp"
	CSHARP        LanguageIdentifier = "csharp"
	CSS           LanguageIdentifier = "css"
	DIFF          LanguageIdentifier = "diff"
	DOCKERFILE    LanguageIdentifier = "dockerfile"
	FSHARP        LanguageIdentifier = "fsharp"
	GIT_COMMIT    LanguageIdentifier = "git-commit"
	GIT_REBASE    LanguageIdentifier = "git-rebase"
	GO            LanguageIdentifier = "go"
	GROOVY        LanguageIdentifier = "groovy"
	HANDLEBARS    LanguageIdentifier = "handlebars"
	HTML          LanguageIdentifier = "html"
	INI           LanguageIdentifier = "ini"
	JAVA          LanguageIdentifier = "java"
	JAVASCRIPT    LanguageIdentifier = "javascript"
	JSON          LanguageIdentifier = "json"
	LATEX         LanguageIdentifier = "latex"
	LESS          LanguageIdentifier = "less"
	LUA           LanguageIdentifier = "lua"
	MAKEFILE      LanguageIdentifier = "makefile"
	MARKDOWN      LanguageIdentifier = "markdown"
	OBJECTIVE_C   LanguageIdentifier = "objective-c"
	OBJECTIVE_CPP LanguageIdentifier = "objective-cpp"
	PERL          LanguageIdentifier = "perl"
	PHP           LanguageIdentifier = "php"
	POWERSHELL    LanguageIdentifier = "powershell"
	PUG           LanguageIdentifier = "jade"
	PYTHON        LanguageIdentifier = "python"
	R             LanguageIdentifier = "r"
	RAZOR         LanguageIdentifier = "razor"
	RUBY          LanguageIdentifier = "ruby"
	RUST          LanguageIdentifier = "rust"
	SASS          LanguageIdentifier = "sass"
	SASSC         LanguageIdentifier = "scss"
	SHADERLAB     LanguageIdentifier = "shaderlab"
	SHELL_SCRIPT  LanguageIdentifier = "shellscript"
	SQL           LanguageIdentifier = "sql"
	SWIFT         LanguageIdentifier = "swift"
	TYPE_SCRIPT   LanguageIdentifier = "typescript"
	TEX           LanguageIdentifier = "tex"
	VB            LanguageIdentifier = "vb"
	XML           LanguageIdentifier = "xml"
	XSL           LanguageIdentifier = "xsl"
	YAML          LanguageIdentifier = "yaml"
)

